### ISSUE TITLE
Can't Authenticate

### ISSUE THREAD

**Issue by DebugDax** [amickael/eero-adguard-sync#3]
Installing with Python 3.9 on Pi 4.

When I run eag-sync sync and provide my email it immediately throws an exception for data['meta']['code'].
I have tried using my phone number as well and it accepts the number but I never receive an SMS code.

My account is linked with Amazon so I am using that email address, which also shows in the Eero app under my account.

```
pi@pi4server:~ $ /home/pi/.local/bin/eag-sync sync --eero-user "email@email.com"
Authenticating Eero...
Traceback (most recent call last):
  File "/home/pi/.local/bin/eag-sync", line 8, in <module>
    sys.exit(cli())
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/eero_adguard_sync/commands/sync.py", line 219, in sync
    user_token = eero_client.login(eero_user)
  File "/home/pi/.local/lib/python3.9/site-packages/eero/eero.py", line 26, in login
    data = self.client.post('login', json=json)
  File "/home/pi/.local/lib/python3.9/site-packages/eero/client.py", line 19, in post
    return self._parse_response(response)
  File "/home/pi/.local/lib/python3.9/site-packages/eero/client.py", line 13, in _parse_response
    raise ClientException(data['meta']['code'],
eero.exception.ClientException
```

**Comment by apearson** [comment]
Accounts linked with Amazon are authenticated differently than pure eero accounts

**Comment by thedsider** [comment]
I get the same error with both an Amazon admin account and an Eero-only admin account;

 /home/phill/.local/bin/eag-sync sync --eero-user "<user>@gmail.com"
Authenticating Eero...
Traceback (most recent call last):
  File "/home/phill/.local/bin/eag-sync", line 8, in <module>
    sys.exit(cli())
  File "/home/phill/.local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/phill/.local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/phill/.local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/phill/.local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/phill/.local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/phill/.local/lib/python3.9/site-packages/eero_adguard_sync/commands/sync.py", line 219, in sync
    user_token = eero_client.login(eero_user)
  File "/home/phill/.local/lib/python3.9/site-packages/eero/eero.py", line 26, in login
    data = self.client.post('login', json=json)
  File "/home/phill/.local/lib/python3.9/site-packages/eero/client.py", line 19, in post
    return self._parse_response(response)
  File "/home/phill/.local/lib/python3.9/site-packages/eero/client.py", line 13, in _parse_response
    raise ClientException(data['meta']['code'],
eero.exception.ClientException

The GMail address is a network admin of the Eero network and is not associated with Amazon in any way - I used the Eero app to create the account.

So unless having _any_ Amazon authed admin on the network causes an issue, using a secondary Eero authed admin should have worked?

**Comment by MastroPino** [comment]
HI there,
I have the same issue and I can't find any information about Amazon auth. Can you pls link us the how to if there is

**Comment by Expatinobz** [comment]
Add a new admin account to the eero app and you remember to use non-Amazon email.
